import Link from "next/link";
import PostMediaPreview from "@/components/route_component/post-media-preview";
import { HiCamera, HiVideoCamera } from 'react-icons/hi';
import { PostCancelComp } from '@/components/sub_componnets/sub/post-cancel-comp.';
import PostEditor from '@/components/route_component/post-editor';
import { Metadata } from 'next';
import NewPostMediaAdd from "@/components/sub_componnets/sub/new-post-media-add";

export const metadata: Metadata = {
    title: "Create Post",
    description: "Generated by create next app",
}

const NewPost = () => {
    return (
        <div className="h-full">
            <PostEditor />
        </div >
    );
};

export default NewPost;
