import PostEditor from '@/components/route_component/post-editor';
import { Metadata } from 'next';

export const metadata: Metadata = {
    title: "Create Post",
    description: "Generated by create next app",
}

const NewPost = () => {
    return (
        <div className="h-full">
            <PostEditor />
        </div >
    );
};

export default NewPost;
