import type { Metadata } from "next";
import { GeistSans } from 'geist/font/sans';
import "./globals.css";
import NavBar from "@/page-components/nav";


export const metadata: Metadata = {
  title: "Admin Panel - Paymefans Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <NavBar />
        <div className="flex-1 space-y-6 p-2 py-4 pt-10 max-w-screen-xl mx-auto">
          {children}
        </div>
      </body>
    </html>
  );
}
