import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { Toaster as SonnerToast } from "sonner"


const font = Inter({ subsets: ["cyrillic", "cyrillic-ext", "greek", "greek-ext", "latin", "latin-ext"], display: "swap", adjustFontFallback: false });


export const metadata: Metadata = {
    title: "Paymefans React Application",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={font.className}>
                <SonnerToast richColors position="top-center"
                    toastOptions={{
                        closeButton: true,
                        duration: 10000,
                        style: {
                            fontSize: "16px",
                            borderRadius: "10px",
                            fontFamily: "system-ui",
                        },
                    }}
                />
                {children}
            </body>
        </html>
    );
}
