import type { Metadata } from "next";
// import { Golos_Text } from "next/font/google";
// const font = Golos_Text({
//     weight: ["400", "500", "600", "700", "800"],
//     display: "auto",
//     subsets: ["latin", "latin-ext"],
// })
import { GeistSans } from 'geist/font/sans';
import "../globals.css";
import MenuButtons from "@/components/route_component/menu_buttons";
import ModalComponent from "@/components/route_component/modalComponent";
import SideModels from "@/components/route_component/side_models";
import Header from "@/components/route_component/header";
import SideBar from "@/components/route_component/sidebar";
import { Toaster } from "react-hot-toast";
import { Toaster as SonnerToast } from "sonner"
import QueryProvider from "@/providers/query-provider";
import getUserData from "@/utils/data/user-data";
import PostComponentPreview from "@/components/post/full-component-preview";
import { UserContextProvider } from "@/lib/userUseContext";
import { UserPointsContextProvider } from "@/contexts/user-points-context";
import { MessagesConversationProvider } from "@/contexts/messages-conversation-context";
import Loader from "@/components/route_component/loader";
import VerificationAlert from "@/components/route_component/verification-alert";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const user = await getUserData();
    return (
        <html lang="en">
            <UserContextProvider user={user}>
                <QueryProvider>
                    <MessagesConversationProvider>
                        <UserPointsContextProvider>
                            <body className={`${GeistSans.className} dark:bg-gray-950`}>
                                <Loader />
                                <Toaster />
                                <SonnerToast richColors position="top-center"
                                    toastOptions={{
                                        closeButton: true,
                                        duration: 10000,
                                        style: {
                                            fontSize: "16px",
                                            borderRadius: "10px",
                                            fontFamily: "system-ui",
                                        },
                                    }}
                                />
                                <div className="relative grid lg:grid-cols-9">
                                    <MessagesConversationProvider>
                                        <div className="col-span-2">
                                            <SideBar />
                                        </div>
                                        <div className="col-span-7 overflow-auto border-r">
                                            <Header />
                                            <div className="grid lg:grid-cols-7">
                                                <div className="col-span-4 md:border-r dark:border-slate-800">
                                                    {children}
                                                </div>
                                                <SideModels />
                                            </div>
                                        </div>
                                    </MessagesConversationProvider>
                                    <MenuButtons />
                                    <ModalComponent />
                                </div>
                                <PostComponentPreview />
                            </body>
                        </UserPointsContextProvider>
                    </MessagesConversationProvider>
                </QueryProvider>
            </UserContextProvider>
        </html>
    );
}
